// <auto-generated />
using System;
using DroneBuilderSimulation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DroneBuilderSimulation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205200943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.Battery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CRating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapacityMah")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellCountS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Batteries");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.DroneBuild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BuildName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EstimatedFlightTimeMinutes")
                        .HasColumnType("REAL");

                    b.Property<double>("EstimatedMaxSpeedKmh")
                        .HasColumnType("REAL");

                    b.Property<int>("FlightControllerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FrameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MotorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropellerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReceiverId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalWeightGrams")
                        .HasColumnType("REAL");

                    b.Property<int?>("VtxId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BatteryId");

                    b.HasIndex("FlightControllerId");

                    b.HasIndex("FrameId");

                    b.HasIndex("MotorId");

                    b.HasIndex("PropellerId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("VtxId");

                    b.ToTable("DroneBuilds");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.FlightController", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EscCurrentRatingAmps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firmware")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("FlightControllers");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.Frame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPropSizeInch")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SizeCategory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.Property<double>("WheelbaseMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Frames");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.Motor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Kv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxContinuousCurrentAmps")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxPowerWatts")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatorSize")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Motors");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.Propeller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BladeCount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DiameterInch")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PitchInch")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Propellers");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.RadioReceiver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("FrequencyGhz")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("RadioReceivers");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.VideoTransmitter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDigital")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxRangeKm")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("PowerMw")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightGrams")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("VideoTransmitters");
                });

            modelBuilder.Entity("DroneBuilderSimulation.Models.Entities.DroneBuild", b =>
                {
                    b.HasOne("DroneBuilderSimulation.Models.Entities.Battery", "Battery")
                        .WithMany()
                        .HasForeignKey("BatteryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DroneBuilderSimulation.Models.Entities.FlightController", "FlightController")
                        .WithMany()
                        .HasForeignKey("FlightControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DroneBuilderSimulation.Models.Entities.Frame", "Frame")
                        .WithMany()
                        .HasForeignKey("FrameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DroneBuilderSimulation.Models.Entities.Motor", "Motor")
                        .WithMany()
                        .HasForeignKey("MotorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DroneBuilderSimulation.Models.Entities.Propeller", "Propeller")
                        .WithMany()
                        .HasForeignKey("PropellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DroneBuilderSimulation.Models.Entities.RadioReceiver", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("DroneBuilderSimulation.Models.Entities.VideoTransmitter", "Vtx")
                        .WithMany()
                        .HasForeignKey("VtxId");

                    b.Navigation("Battery");

                    b.Navigation("FlightController");

                    b.Navigation("Frame");

                    b.Navigation("Motor");

                    b.Navigation("Propeller");

                    b.Navigation("Receiver");

                    b.Navigation("Vtx");
                });
#pragma warning restore 612, 618
        }
    }
}
